### ISSUE TITLE
Посмотреть ButterKnife

### ISSUE THREAD

**Issue by lampaa** [FUCTAIIIK0/chat#5]
Крутая штука, которая избавляет от явной инициализации вьюх:
![image](https://user-images.githubusercontent.com/927585/63154739-f3e38380-c019-11e9-8794-d0f00bfd834d.png)
и как у меня

![image](https://user-images.githubusercontent.com/927585/63154807-1d041400-c01a-11e9-9f0c-f5c4f4763ba8.png)

**Comment by FUCTAIIIK0** [comment]
готово
