### ISSUE TITLE
Привести отступы в порядок

### ISSUE THREAD

**Issue by lampaa** [FUCTAIIIK0/chat#6]
![image](https://user-images.githubusercontent.com/927585/63155001-74a27f80-c01a-11e9-80a8-1d49a6fd8086.png)

Отступы должны ровняться 4 пробелам

![image](https://user-images.githubusercontent.com/927585/63155029-8126d800-c01a-11e9-9010-e10e222c1da3.png)

**Comment by FUCTAIIIK0** [comment]
сделал
